name: foot_food
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.3

  # HTTP клиент для работы с API
  http: ^1.2.0

  # SVG поддержка
  flutter_svg: ^2.0.9

  # Выбор изображений из галереи
  image_picker: ^1.0.7

  # Форматирование дат
  intl: ^0.19.0

  # Хранение настроек (для проверки первого запуска)
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Изображения
  assets:
    - assets/images/
    - assets/images/placeholder_food.png
    - assets/images/placeholder_restaurant.png
    - assets/images/logo.png
    - assets/images/logodark.png
    - assets/images/splash.png
    - assets/images/reg:auth.png
    - assets/images/regcli.png
    - assets/images/regsell.png
    - assets/images/auth.png
    - assets/images/buyerHome.png
    - assets/images/sellerHome.png
    - assets/images/Vector.svg
    - assets/images/icon people.svg
    - assets/images/icon coin.svg
    - assets/images/search.svg
    - assets/images/searchgreen.svg
    - assets/images/filtergreen.svg
    - assets/images/firstenter1.png
    - assets/images/firstenter2.png
    - assets/images/firstenter3.png
    - assets/images/firstenter4.png
    - assets/images/firstenterRoands.png

  # Шрифты
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Jura
      fonts:
        - asset: fonts/Jura-Regular.ttf
          weight: 400
        - asset: fonts/Jura-Medium.ttf
          weight: 500
        - asset: fonts/Jura-Bold.ttf
          weight: 700
